### ISSUE TITLE
二维码扫面退回的时候，报错，emmmmmm

### ISSUE THREAD

**Issue by helloworkcupid** [Tamsiree/RxTool#101]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendMessage(android.os.Message)' on a null object reference
                                                     at android.os.Message.sendToTarget(Message.java:416)
                                                     at com.vondear.rxtools.module.scaner.DecodeHandler.decode(DecodeHandler.java:156)
                                                     at com.vondear.rxtools.module.scaner.DecodeHandler.handleMessage(DecodeHandler.java:115)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:159)
                                                     at com.vondear.rxtools.module.scaner.DecodeThread.run(DecodeThread.java:39)

**Comment by JinZhao93** [comment]
+1

**Comment by HouChengYue** [comment]
我也有用这个扫码，不过我重写了扫描的页面，退回没问题。

**Comment by dyn654466499** [comment]
应该是退出页面的时候，handler被置为null了。
protected void onPause() {
        super.onPause();
        if (this.handler != null) {
            this.handler.quitSynchronously();
            this.handler = null;
        }

        CameraManager.get().closeDriver();
    }

**Comment by chuanjiangzhou** [comment]
+1
