### ISSUE TITLE
二维码扫描点击返回就崩溃。。。

### ISSUE THREAD

**Issue by fightcoder** [Tamsiree/RxTool#108]

**Comment by dyn654466499** [comment]
你初始化了没有，调用RxTools.init

**Comment by zhangxianpeng** [comment]
已经初始化了，返回的时候显示为空指针报错

**Comment by Key-CN** [comment]
是的。我也发现这个问题了，扫描返回是以下报错
`05-28 16:40:11.182 30697-30859/com.vondear.tools E/AndroidRuntime: FATAL EXCEPTION: Thread-3946
    Process: com.vondear.tools, PID: 30697
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendMessage(android.os.Message)' on a null object reference
        at android.os.Message.sendToTarget(Message.java:429)
        at com.vondear.rxtools.module.scaner.DecodeHandler.decode(DecodeHandler.java:159)
        at com.vondear.rxtools.module.scaner.DecodeHandler.handleMessage(DecodeHandler.java:116)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:224)
        at com.vondear.rxtools.module.scaner.DecodeThread.run(DecodeThread.java:39)`

**Comment by Key-CN** [comment]
`if (message.getTarget() != null) {
                message.sendToTarget();
            }`

我在报错行加了判断，虽然不报错了。但是来找issue主要还是想搞清楚没有target的原因

**Comment by WLDragon** [comment]
ActivityScanerCode在onPause的时候把handler设置为null了，但是DecodeThread的Loop还在执行，所以DecodeHandler发消息的时候找不到对象，自己判断一下就好
```
if(activity.getHandler() != null) {
  Message message = Message.obtain(activity.getHandler(), R.id.decode_failed);
  message.sendToTarget();
}
```
我试过在handleMessage里这样写，明明没有异步代码，一样报错，我不是做java开发的，搞不懂
```
if(activity.getHandler() != null){
  decode((byte[]) message.obj, message.arg1, message.arg2);
}
```
