### ISSUE TITLE
一加6t，点击联系人侧边快速导航就闪退

### ISSUE THREAD

**Issue by wananxin** [Tamsiree/RxTool#195]

**Comment by qr973440230** [comment]
huawei 荣耀V10也同样闪退

**Comment by zhaoxiuyu** [comment]
huawei mate 20 pro 也同样闪退

**Comment by checkming** [comment]
小米8 也一样ANR 无响应

**Comment by haohao123456** [comment]
> _No description provided._

我也下载了项目，点击这一功能也崩溃了，
我的是一加5，安卓9.0，系统版本28
代作者回答一下，崩溃是因为版本过高的问题
根据报错，百度一下，找到对应的解决方法
    java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipRect(Canvas.java:826)
        at com.vondear.rxui.view.sidebar.PinnedHeaderDecoration.onDrawOver(PinnedHeaderDecoration.java:60)
根据报错，**Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed**
找到相似的解决方法，试一下就能解决的了
[**Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed**](https://blog.csdn.net/mp624183768/article/details/85256257)

**Comment by haohao123456** [comment]
> huawei 荣耀V10也同样闪退

我也下载了项目，点击这一功能也崩溃了，
我的是一加5，安卓9.0，系统版本28
代作者回答一下，崩溃是因为版本过高的问题
根据报错，百度一下，找到对应的解决方法
    java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipRect(Canvas.java:826)
        at com.vondear.rxui.view.sidebar.PinnedHeaderDecoration.onDrawOver(PinnedHeaderDecoration.java:60)
根据报错，**Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed**
找到相似的解决方法，试一下就能解决的了
[**Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed**](https://blog.csdn.net/mp624183768/article/details/85256257)

**Comment by haohao123456** [comment]
> huawei mate 20 pro 也同样闪退

> huawei 荣耀V10也同样闪退

我也下载了项目，点击这一功能也崩溃了，
我的是一加5，安卓9.0，系统版本28
代作者回答一下，崩溃是因为版本过高的问题
根据报错，百度一下，找到对应的解决方法
    java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipRect(Canvas.java:826)
        at com.vondear.rxui.view.sidebar.PinnedHeaderDecoration.onDrawOver(PinnedHeaderDecoration.java:60)
根据报错，**Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed**
找到相似的解决方法，试一下就能解决的了
[**Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed**](https://blog.csdn.net/mp624183768/article/details/85256257)

**Comment by haohao123456** [comment]
> 小米8 也一样 闪退

> huawei 荣耀V10也同样闪退

我也下载了项目，点击这一功能也崩溃了，
我的是一加5，安卓9.0，系统版本28
代作者回答一下，崩溃是因为版本过高的问题
根据报错，百度一下，找到对应的解决方法
    java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipRect(Canvas.java:826)
        at com.vondear.rxui.view.sidebar.PinnedHeaderDecoration.onDrawOver(PinnedHeaderDecoration.java:60)
根据报错，**Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed**
找到相似的解决方法，试一下就能解决的了
[**Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed**](https://blog.csdn.net/mp624183768/article/details/85256257)
