### ISSUE TITLE
安卓10 的设备上已经成功获取权限了,但是拍照或者选择相册的时候返回图片还是提示权限拒绝

### ISSUE THREAD

**Issue by clbDream** [Tamsiree/RxTool#262]

**Comment by clbDream** [comment]
2020-08-31 15:50:20.027 8375-8375/com.tamsiree.rxdemo E/TransformImageView: onFailure: setImageUri
    java.io.FileNotFoundException: open failed: EACCES (Permission denied)
        at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:315)
        at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:220)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1498)
        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1338)
        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1286)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:100)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
