### ISSUE TITLE
Android 6.0设置头像，返回拿不到图片

### ISSUE THREAD

**Issue by liyangyang123** [Tamsiree/RxTool#84]
onFailure: setImageUri
                                                                       java.lang.IllegalArgumentException: Bounds for bitmap could not be retrieved from the Uri: [file:///storage/emulated/0/Pictures/HuadaoSignature/huadao_1516243267408.jpg]
                                                                           at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:113)
                                                                           at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:41)
                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                           at java.lang.Thread.run(Thread.java:818)

**Comment by steveLzsLR** [comment]
这不是很明显了嘛，不支持“file:///storage/emulated/0/Pictures/HuadaoSignature/huadao_1516243267408.jpg”这样的uri,换成网络url试试

**Comment by liyangyang123** [comment]
没找到在哪里转换的，求助
